package org.example.day13.exception;

public class Problem2 {
    public static void main(String[] args) throws Exception1 {
        System.out.println("1. 작동 잘 될 예정");

        System.out.println("2. 문제 발생 코드" + 10 / 0);

        System.out.println("3. 나는 과연 프린트 될까용?");
    }
}
